config/routes.rb
# frozen_string_literal: true

# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
    get '/login' => 'login#login', :as => :login
    get '/login/google', to: redirect('auth/google_oauth2'), as: :google_login
    get '/login/github', to: redirect('auth/github'), as: :github_login
    get '/auth/google_oauth2/callback', to: 'login#google_oauth2', as: :google_oauth2_callback
    get '/auth/github/callback', to: 'login#github', as: :github_callback
    get '/logout' => 'login#logout', :as => :logout
    get '/user/profile', to: 'user#profile', as: :user_profile

    root to: 'map#index', as: 'root'
    get '/state/:state_symbol' => 'map#state', :as => :state_map
    get '/state/:state_symbol/county/' => 'map#county', :as => :map_county


    get '/ajax/state/:state_symbol' => 'ajax#counties'

    # Routes for Events
    resources :events, only: %i[index show]
    get '/my_events/new' => 'my_events#new', :as => :new_my_event
    match '/my_events/new', to: 'my_events#create', via: [:post]
    get '/my_events/:id' => 'my_events#edit', :as => :edit_my_event
    match '/my_events/:id', to: 'my_events#update', via: %i[put patch]
    match '/my_events/:id', to: 'my_events#destroy', via: [:delete]

    # Routes for Representatives
    resources :representatives, only: [:index]
    resources :representatives do
        resources :news_items, only: %i[index show]
        get '/representatives/:representative_id/my_news_item/new' => 'my_news_items#new',
            :as                                                    => :new_my_news_item
        match '/representatives/:representative_id/my_news_item/new', to:  'my_news_items#top_articles',
                                                                      via: [:post]
        get '/representatives/:representative_id/my_news_item/add' => 'my_news_items#top_articles',
            :as                                                    => :add_my_top_news_item
        match '/representatives/:representative_id/my_news_item/add', to:  'my_news_items#create',
                                                                      via: [:post]
        get '/representatives/:representative_id/my_news_item/:id' => 'my_news_items#edit',
            :as                                                    => :edit_my_news_item
        match '/representatives/:representative_id/my_news_item/:id', to:  'my_news_items#update',
                                                                      via: %i[put patch]
        match '/representatives/:representative_id/my_news_item/:id', to:  'my_news_items#destroy',
                                                                      via: [:delete]
    end
    get '/search/(:address)' => 'search#search', :as => 'search_representatives'

    get '/state/:state_symbol/county/:std_fips_code' => 'search#search_using_county', :as => :county

end

app/controllers/my_news_items_controller.rb
# frozen_string_literal: true

require 'news-api'

class MyNewsItemsController < SessionController
  before_action :set_representative
  before_action :set_representatives_list
  before_action :set_issues_list, only: %i[new edit]
  before_action :set_news_item, only: %i[edit update destroy]

  def new
    @news_item = NewsItem.new
  end

  def edit; end

  def create
    @news_item = make_news_item
    @representative = Representative.find(params[:representative_id])
    if @news_item.save
      unless params[:rating].nil?
        Rating.add_rating({ rating: params[:rating], user_id: session[:current_user_id], news_item_id: @news_item.id })
      end
      redirect_to representative_news_item_path(@representative, @news_item),
                  notice: 'News item was successfully created.'
    else
      render :new, error: 'An error occurred when creating the news item.'
    end
  end

  def update
    if @news_item.update(news_item_params)
      redirect_to representative_news_item_path(@representative, @news_item),
                  notice: 'News item was successfully updated.'
    else
      render :edit, error: 'An error occurred when updating the news item.'
    end
  end

  def destroy
    @news_item.destroy
    redirect_to representative_news_items_path(@representative),
                notice: 'News was successfully destroyed.'
  end

  def top_articles
    news_item = params[:news_item]
    @news_item = params[:news_item]
    @representative_id = news_item[:representative_id]
    @issue = news_item[:issue]
    @representative = Representative.find(@representative_id)
    @representative_name = @representative.name
    news_api = News.new(Rails.application.credentials[:NEWS_API_KEY])
    query = "#{@representative_name} #{@issue}"

    top_headlines = news_api.get_everything(q:        query,
                                            language: 'en',
                                            sortBy:   'relevancy')
    top_headlines = top_headlines.slice(0, 5) if top_headlines.length > 5
    @top_articles_list = top_headlines.map do |article|
      {
        title:       article.title,
        description: article.description,
        link:        article.url
      }
    end
  end

  private

  def set_issues_list
    @issues_list = NewsItem.all_issues
  end

  def set_representative
    @representative = Representative.find(
      params[:representative_id]
    )
  end

  def make_news_item
    article = JSON.parse(params[:article])
    params[:news_item] =
      { title: article['title'], link: article['link'], issue: params[:issue], description: article['description'],
representative_id: params[:representative_id] }
    @news_item = NewsItem.find_by(link: article['link'])
    @news_item = NewsItem.new(news_item_params) if @news_item.nil?
    @news_item
  end

  def set_representatives_list
    @representatives_list = Representative.all.map { |r| [r.name, r.id] }
  end

  def set_news_item
    @news_item = NewsItem.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def news_item_params
    params.require(:news_item).permit(:news, :title, :issue, :description, :link, :representative_id)
  end
end

app/views/my_news_items/_form.html.haml
= form_for news_item, url: form_url, html: { method: form_method } do |f|
    - if news_item.errors.any?
        .alert.alert-danger
            %h2
                "#{pluralize(news_item.errors.count, 'error')} prohibited this news from being saved:"
            %ul
                - news_item.errors.full_messages.each do |message|
                    %li= message
    .form-group.row
        .col-sm-2
            = label :news_item, :title, 'Title:', class: 'col-form-label'
        .col-sm-10
            = text_field :news_item, :title, { class: 'form-control', placeholder: 'Brief title of article...' }
    .form-group.row
        .col-sm-2
            = label :news_item, :link, 'Link', class: 'col-form-label'
        .col-sm-10
            = text_field :news_item, :link, { class: 'form-control', placeholder: 'Link to external article...' }
    .form-group.row
        .col-sm-2
            = label :news_item, :issue, class: 'col-form-label'
        .col-sm-10
            = select :news_item, :issue, issues_list, { include_blank: true },
            class: 'form-control'
    .form-group.row
        .col-sm-2
            = label :news_item, :description, class: 'col-form-label'
        .col-sm-10
            = text_area :news_item, :description, { class: 'form-control',
            placeholder: 'Describe the contents of the article...' }
    .form-group.row
        .col-sm-2
            = label :news_item, :representative_id, class: 'col-form-label'
        .col-sm-10
            = select :news_item, :representative_id, representatives_list, { include_blank: true },
            class: 'form-control'
    .actions
        = f.submit 'Save', class: 'btn btn-primary'

app/views/my_news_items/_formshort.html.haml
= form_for news_item, url: form_url, html: { method: form_method } do |f|
    - if news_item.errors.any?
        .alert.alert-danger
            %h2
                "#{pluralize(news_item.errors.count, 'error')} prohibited this news from being saved:"
            %ul
                - news_item.errors.full_messages.each do |message|
                    %li= message
    .form-group.row
        .col-sm-2
            = label :news_item, :representative_name, class: 'col-form-label'
        .col-sm-10
            = select :news_item, :representative_id, representatives_list, { include_blank: true },
            class: 'form-control'
    .form-group.row
        .col-sm-2
            = label :news_item, :issue, class: 'col-form-label'
        .col-sm-10
            = select :news_item, :issue, issues_list, { include_blank: true },
            class: 'form-control'
    .actions
        = f.submit 'Search', class: 'btn btn-primary'

app/views/my_news_items/edit.html.haml
.row.mt-2
    .col-12.col-md-6.offset-md-3.col-xl-4.offset-xl-4
        %h1.text-center Edit news article

    .col-12.col-md-6.offset-md-3.col-xl-4.offset-xl-4
        = render 'form', news_item: @news_item,
         form_url: representative_edit_my_news_item_path(@representative, @news_item),
         form_method: :put,
         representatives_list: @representatives_list,
         issues_list: @issues_list

    .col-12.col-md-6.offset-md-3.col-xl-4.offset-xl-4
        .clearfix.mt-3
            .float-right
                = link_to representative_news_item_path(@representative, @news_item), class: 'mx-1 btn btn-info' do
                    Show article
                    %i.fas.fa-eye
                = link_to representative_news_items_path(@representative), class: 'mx-1 btn btn-info' do
                    View all news articles
                    %i.fas.fa-arrow-right

app/views/my_news_items/new.html.haml
.row.mt-2
    .col-12.col-md-6.offset-md-3.col-xl-4.offset-xl-4
        %h1.text-center Edit news article

    .col-12.col-md-6.offset-md-3.col-xl-4.offset-xl-4
        = render 'formshort', news_item: @news_item,
        form_url: representative_new_my_news_item_path(@representative),
        form_method: :post,
        representatives_list: @representatives_list,
        issues_list: @issues_list

app/views/my_news_items/top_articles.html.erb
<div>
    <div class="justify-content-center text-center">
        <h1>Edit News Item</h1>
    <div>
    <p><strong>Representative: </strong><%=@representative_name%></p>
    <p><strong>Issue: </strong><%=@issue%></p>
    <p>Select An Article:</p>
    <%= form_tag(representative_add_my_top_news_item_path(@representative)) do |f| %>
      <%= hidden_field_tag 'issue', @issue %>
      <%= hidden_field_tag :news_item, @news_item %>
      <div class="mx-auto">
        <% @top_articles_list.each do |article| %>
          <div class=" mx-auto w-50 p-3 ml-10 text-center">
            <%= radio_button_tag 'article', article.to_json, false, class: "form-check-input" %>
            <div class="w-90 p-3" style="background-color: #eee;" style="text-align: left;">
              <p><strong>Title:</strong><%=article[:title]%></p>
              <a href=<%=article[:link]%>>Link</a>
              <p><strong>Description:</strong><%=article[:description]%></p>
            </div>
          </div>
        <% end %>
      <div>
      <label for="ratings">Rating</label>
      <%= select_tag(:rating, options_for_select([["1",1],["2",2],["3",3], ["4", 4], ["5", 5]]), class:"select") %>
      <%= submit_tag("Save", class: "btn btn-large btn-primary") %>
    <% end %>
</div>